name: Update Inventory Info
on: [push]

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Skript ausführbar machen
        run: chmod +x ./.github/scripts/show-container-releases.sh

      - name: run container
        id: check
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "$(pwd)"
          ls -al
          echo "### Package Inventory (Stand: $(date +"%Y-%m-%d"))" > ./PackageInventory.md

      - name: Container starten und Skript ausführen (Alpine)
        run: |
          podman run --rm \
            -v "$(pwd):/out:z" \
            -w /out:z \
            --entrypoint /bin/sh \
            ghcr.io/widukind42/ytdlp_alpine \
            ./github/scripts/show-container-releases.sh > ./PackageInventory.md

      - name: Änderungen commiten
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add PackageInventory.md
          git commit -m "Update release info [skip ci]"
          git push
